INFO: 2020-06-27 09:05:57,553: main() 'Using profile folder /home/saul/.config/variety/'
INFO: 2020-06-27 09:05:57,558: perform_upgrade() 'Last run version was 0.8.3 or earlier, current version is 0.8.3'
INFO: 2020-06-27 09:05:57,755: process_command() 'Received command: []'
INFO: 2020-06-27 09:05:57,757: load_banned() 'Missing or invalid banned URLs list, no URLs will be banned'
INFO: 2020-06-27 09:05:57,768: start() 'Using data_path /usr/share/variety'
INFO: 2020-06-27 09:05:57,768: load() 'Jumble loading'
INFO: 2020-06-27 09:05:57,768: _walk_modules() 'Jumble loading module in __init__ from /usr/lib/python3.8/site-packages/variety/plugins/builtin/__init__.py'
INFO: 2020-06-27 09:05:57,769: _walk_modules() 'Jumble loading module in APODDownloader from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/APODDownloader.py'
INFO: 2020-06-27 09:05:57,770: load() 'Jumble found plugin class: <class 'APODDownloader.APODDownloader'>: {'name': 'APODDownloader', 'description': 'NASA Astro Pic of the Day', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-06-27 09:05:57,770: _walk_modules() 'Jumble loading module in BingDownloader from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/BingDownloader.py'
INFO: 2020-06-27 09:05:57,771: load() 'Jumble found plugin class: <class 'BingDownloader.BingDownloader'>: {'name': 'BingDownloader', 'description': 'Bing Photo of the Day', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-06-27 09:05:57,771: _walk_modules() 'Jumble loading module in ChromeOSWallpapersDownloader from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/ChromeOSWallpapersDownloader.py'
INFO: 2020-06-27 09:05:57,772: load() 'Jumble found plugin class: <class 'ChromeOSWallpapersDownloader.ChromeOSWallpapersDownloader'>: {'name': 'ChromeOsWallpapersDownloader', 'description': 'Chrome OS Wallpapers', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-06-27 09:05:57,772: _walk_modules() 'Jumble loading module in DesktopprDownloader from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/DesktopprDownloader.py'
INFO: 2020-06-27 09:05:57,773: load() 'Jumble found plugin class: <class 'DesktopprDownloader.DesktopprDownloader'>: {'name': 'DesktopprDownloader', 'description': 'Random wallpapers from Desktoppr.co', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-06-27 09:05:57,773: _walk_modules() 'Jumble loading module in EarthviewDownloader from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/EarthviewDownloader.py'
INFO: 2020-06-27 09:05:57,774: load() 'Jumble found plugin class: <class 'EarthviewDownloader.EarthviewDownloader'>: {'name': 'EarthviewDownloader', 'description': 'Google Earth View Wallpapers', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-06-27 09:05:57,774: _walk_modules() 'Jumble loading module in MediaRSSDownloader from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/MediaRSSDownloader.py'
INFO: 2020-06-27 09:05:57,775: _walk_modules() 'Jumble loading module in MediaRSSSource from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/MediaRSSSource.py'
INFO: 2020-06-27 09:05:57,789: load() 'Jumble found plugin class: <class 'MediaRSSSource.MediaRSSSource'>: {'name': 'MediaRSSSource', 'description': 'Configurable source for fetching images from MediaRSS feeds', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-06-27 09:05:57,789: _walk_modules() 'Jumble loading module in RedditDownloader from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/RedditDownloader.py'
INFO: 2020-06-27 09:05:57,790: _walk_modules() 'Jumble loading module in RedditSource from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/RedditSource.py'
INFO: 2020-06-27 09:05:57,791: load() 'Jumble found plugin class: <class 'RedditSource.RedditSource'>: {'name': 'RedditSource', 'description': 'Configurable source for fetching images from Reddit', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-06-27 09:05:57,791: _walk_modules() 'Jumble loading module in UnsplashConfigurableSource from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/UnsplashConfigurableSource.py'
INFO: 2020-06-27 09:05:57,793: load() 'Jumble found plugin class: <class 'UnsplashConfigurableSource.UnsplashConfigurableSource'>: {'name': 'UnsplashConfigurableSource', 'description': 'Configurable source for fetching photos from Unsplash.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-06-27 09:05:57,793: _walk_modules() 'Jumble loading module in UnsplashDownloader from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/UnsplashDownloader.py'
INFO: 2020-06-27 09:05:57,794: load() 'Jumble found plugin class: <class 'UnsplashDownloader.UnsplashDownloader'>: {'name': 'UnsplashDownloader', 'description': 'High-resolution photos from Unsplash.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-06-27 09:05:57,794: _walk_modules() 'Jumble loading module in WallhavenDownloader from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/WallhavenDownloader.py'
INFO: 2020-06-27 09:05:57,795: _walk_modules() 'Jumble loading module in WallhavenSource from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/WallhavenSource.py'
INFO: 2020-06-27 09:05:57,796: load() 'Jumble found plugin class: <class 'WallhavenSource.WallhavenSource'>: {'name': 'MediaRSSSource', 'description': 'Configurable source for fetching images from Wallhaven.cc', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-06-27 09:05:57,796: _walk_modules() 'Jumble loading module in __init__ from /usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/__init__.py'
INFO: 2020-06-27 09:05:57,797: _walk_modules() 'Jumble loading module in FortuneSource from /usr/lib/python3.8/site-packages/variety/plugins/builtin/quotes/FortuneSource.py'
INFO: 2020-06-27 09:05:57,797: load() 'Jumble found plugin class: <class 'FortuneSource.FortuneSource'>: {'name': 'UNIX fortune program', 'description': 'Displays quotes using the UNIX fortune program. You may want to install additional fortune packs, e.g. fortunes-bofh-excuses.', 'author': 'Dan Jones', 'version': '0.1'}'
INFO: 2020-06-27 09:05:57,797: _walk_modules() 'Jumble loading module in GoodreadsSource from /usr/lib/python3.8/site-packages/variety/plugins/builtin/quotes/GoodreadsSource.py'
INFO: 2020-06-27 09:05:57,805: load() 'Jumble found plugin class: <class 'GoodreadsSource.GoodreadsSource'>: {'name': 'Goodreads', 'description': 'Fetches quotes from Goodreads.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-06-27 09:05:57,806: _walk_modules() 'Jumble loading module in LocalFilesSource from /usr/lib/python3.8/site-packages/variety/plugins/builtin/quotes/LocalFilesSource.py'
INFO: 2020-06-27 09:05:57,806: load() 'Jumble found plugin class: <class 'LocalFilesSource.LocalFilesSource'>: {'name': 'Local text files', 'description': 'Displays quotes, defined in local text files.\nPut your own txt files in: ~/.config/variety/pluginconfig/quotes/.\nThe file format is:\n\nquote -- author\n.\nsecond quote -- another author\n.\netc...\n\nExample: http://rvelthuis.de/zips/quotes.txt', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-06-27 09:05:57,807: _walk_modules() 'Jumble loading module in QuotationsPageSource from /usr/lib/python3.8/site-packages/variety/plugins/builtin/quotes/QuotationsPageSource.py'
INFO: 2020-06-27 09:05:57,808: load() 'Jumble found plugin class: <class 'QuotationsPageSource.QuotationsPageSource'>: {'name': 'TheQuotationsPage.com', 'description': 'Fetches quotes from TheQuotationsPage.com', 'author': 'Peter Levi', 'version': '0.1'}'
INFO: 2020-06-27 09:05:57,808: _walk_modules() 'Jumble loading module in UrbanDictionarySource from /usr/lib/python3.8/site-packages/variety/plugins/builtin/quotes/UrbanDictionarySource.py'
INFO: 2020-06-27 09:05:57,808: load() 'Jumble found plugin class: <class 'UrbanDictionarySource.UrbanDictionarySource'>: {'name': 'Urban Dictionary', 'description': 'Displays definitions from Urban Dictionary', 'author': 'James Miller', 'version': '0.1'}'
INFO: 2020-06-27 09:05:57,809: _walk_modules() 'Jumble loading module in __init__ from /usr/lib/python3.8/site-packages/variety/plugins/builtin/quotes/__init__.py'
INFO: 2020-06-27 09:05:57,812: reload_config() 'Creating new downloader for type bing, location Bing Photo of the Day'
INFO: 2020-06-27 09:05:57,812: reload_config() 'Creating new downloader for type chromeos, location Chrome OS Wallpapers'
INFO: 2020-06-27 09:05:57,812: reload_config() 'Creating new downloader for type earthview, location Google Earth View Wallpapers'
INFO: 2020-06-27 09:05:57,813: log_options() 'Loaded options:'
INFO: 2020-06-27 09:05:57,813: log_options() 'change_enabled = False'
INFO: 2020-06-27 09:05:57,813: log_options() 'change_interval = 300'
INFO: 2020-06-27 09:05:57,813: log_options() 'change_on_start = True'
INFO: 2020-06-27 09:05:57,813: log_options() 'clipboard_enabled = False'
INFO: 2020-06-27 09:05:57,813: log_options() 'clipboard_hosts = ['wallhaven.cc', 'ns223506.ovh.net', 'wallpapers.net', 'flickr.com', 'imgur.com', 'deviantart.com', 'interfacelift.com', 'vladstudio.com', 'imageshack.us']'
INFO: 2020-06-27 09:05:57,813: log_options() 'clipboard_use_whitelist = True'
INFO: 2020-06-27 09:05:57,813: log_options() 'clock_date_font = Ubuntu Condensed, 30'
INFO: 2020-06-27 09:05:57,813: log_options() 'clock_enabled = False'
INFO: 2020-06-27 09:05:57,813: log_options() 'clock_filter = -density 100 -font `fc-match -f '%{file[0]}' '%CLOCK_FONT_NAME'` -pointsize %CLOCK_FONT_SIZE -gravity SouthEast -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+108] '%H:%M' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+110] '%H:%M' -font `fc-match -f '%{file[0]}' '%DATE_FONT_NAME'` -pointsize %DATE_FONT_SIZE -fill '#00000044' -annotate 0x0+[%HOFFSET+58]+[%VOFFSET+58] '%A, %B %d' -fill white -annotate 0x0+[%HOFFSET+60]+[%VOFFSET+60] '%A, %B %d''
INFO: 2020-06-27 09:05:57,813: log_options() 'clock_font = Ubuntu Condensed, 70'
INFO: 2020-06-27 09:05:57,813: log_options() 'configfile = /home/saul/.config/variety/variety.conf'
INFO: 2020-06-27 09:05:57,813: log_options() 'copyto_enabled = False'
INFO: 2020-06-27 09:05:57,813: log_options() 'copyto_folder = Default'
INFO: 2020-06-27 09:05:57,813: log_options() 'desired_color = [160, 160, 160]'
INFO: 2020-06-27 09:05:57,813: log_options() 'desired_color_enabled = False'
INFO: 2020-06-27 09:05:57,813: log_options() 'download_folder = /home/saul/Pictures/wallpaper'
INFO: 2020-06-27 09:05:57,813: log_options() 'download_preference_ratio = 0.9'
INFO: 2020-06-27 09:05:57,813: log_options() 'favorites_folder = /home/saul/.config/variety/Favorites'
INFO: 2020-06-27 09:05:57,813: log_options() 'favorites_operations = [['Downloaded', 'Copy'], ['Fetched', 'Move'], ['Others', 'Copy']]'
INFO: 2020-06-27 09:05:57,813: log_options() 'fetched_folder = /home/saul/.config/variety/Fetched'
INFO: 2020-06-27 09:05:57,813: log_options() 'filters = [[False, 'Keep original', ''], [False, 'Grayscale', '-type Grayscale'], [False, 'Heavy blur', '-blur 120x40'], [False, 'Soft blur', '-blur 20x7'], [False, 'Oil painting', '-paint 8'], [False, 'Pencil sketch', '-colorspace gray \\( +clone -tile ~/.config/variety/pencil_tile.png -draw "color 0,0 reset" +clone +swap -compose color_dodge -composite \\) -fx \'u*.2+v*.8\''], [False, 'Pointilism', '-spread 10 -noise 3'], [False, 'Pixellate', '-scale 3% -scale 3333%']]'
INFO: 2020-06-27 09:05:57,813: log_options() 'icon = None'
INFO: 2020-06-27 09:05:57,813: log_options() 'lightness_enabled = False'
INFO: 2020-06-27 09:05:57,813: log_options() 'lightness_mode = 0'
INFO: 2020-06-27 09:05:57,814: log_options() 'min_rating = 4'
INFO: 2020-06-27 09:05:57,814: log_options() 'min_rating_enabled = False'
INFO: 2020-06-27 09:05:57,814: log_options() 'min_size = 80'
INFO: 2020-06-27 09:05:57,814: log_options() 'min_size_enabled = False'
INFO: 2020-06-27 09:05:57,814: log_options() 'quota_enabled = False'
INFO: 2020-06-27 09:05:57,814: log_options() 'quota_size = 500'
INFO: 2020-06-27 09:05:57,814: log_options() 'quotes_authors = '
INFO: 2020-06-27 09:05:57,814: log_options() 'quotes_bg_color = [80, 80, 80]'
INFO: 2020-06-27 09:05:57,814: log_options() 'quotes_bg_opacity = 55'
INFO: 2020-06-27 09:05:57,814: log_options() 'quotes_change_enabled = False'
INFO: 2020-06-27 09:05:57,814: log_options() 'quotes_change_interval = 300'
INFO: 2020-06-27 09:05:57,814: log_options() 'quotes_disabled_sources = ['Urban Dictionary']'
INFO: 2020-06-27 09:05:57,814: log_options() 'quotes_enabled = False'
INFO: 2020-06-27 09:05:57,814: log_options() 'quotes_favorites_file = /home/saul/.config/variety/favorite_quotes.txt'
INFO: 2020-06-27 09:05:57,814: log_options() 'quotes_font = Bitstream Charter 30'
INFO: 2020-06-27 09:05:57,814: log_options() 'quotes_hpos = 100'
INFO: 2020-06-27 09:05:57,814: log_options() 'quotes_max_length = 250'
INFO: 2020-06-27 09:05:57,814: log_options() 'quotes_tags = '
INFO: 2020-06-27 09:05:57,814: log_options() 'quotes_text_color = [255, 255, 255]'
INFO: 2020-06-27 09:05:57,814: log_options() 'quotes_text_shadow = False'
INFO: 2020-06-27 09:05:57,814: log_options() 'quotes_vpos = 40'
INFO: 2020-06-27 09:05:57,814: log_options() 'quotes_width = 70'
INFO: 2020-06-27 09:05:57,814: log_options() 'safe_mode = False'
INFO: 2020-06-27 09:05:57,814: log_options() 'slideshow_custom_enabled = False'
INFO: 2020-06-27 09:05:57,814: log_options() 'slideshow_custom_folder = /home/saul/Pictures'
INFO: 2020-06-27 09:05:57,814: log_options() 'slideshow_downloads_enabled = False'
INFO: 2020-06-27 09:05:57,814: log_options() 'slideshow_fade = 0.4'
INFO: 2020-06-27 09:05:57,814: log_options() 'slideshow_favorites_enabled = True'
INFO: 2020-06-27 09:05:57,814: log_options() 'slideshow_mode = Fullscreen'
INFO: 2020-06-27 09:05:57,814: log_options() 'slideshow_monitor = All'
INFO: 2020-06-27 09:05:57,814: log_options() 'slideshow_pan = 0.05'
INFO: 2020-06-27 09:05:57,814: log_options() 'slideshow_seconds = 6.0'
INFO: 2020-06-27 09:05:57,815: log_options() 'slideshow_sort_order = Random'
INFO: 2020-06-27 09:05:57,815: log_options() 'slideshow_sources_enabled = True'
INFO: 2020-06-27 09:05:57,815: log_options() 'slideshow_zoom = 0.2'
INFO: 2020-06-27 09:05:57,815: log_options() 'smart_enabled = False'
INFO: 2020-06-27 09:05:57,815: log_options() 'smart_notice_shown = False'
INFO: 2020-06-27 09:05:57,815: log_options() 'smart_register_shown = False'
INFO: 2020-06-27 09:05:57,815: log_options() 'sources = [[False, 'favorites', 'The Favorites folder'], [False, 'fetched', 'The Fetched folder'], [False, 'folder', '/usr/share/backgrounds'], [False, 'desktoppr', 'Random wallpapers from Desktoppr.co'], [True, 'bing', 'Bing Photo of the Day'], [False, 'unsplash', 'High-resolution photos from Unsplash.com'], [False, 'apod', "NASA's Astronomy Picture of the Day"], [False, 'flickr', 'user:www.flickr.com/photos/peter-levi/;user_id:93647178@N00;'], [True, 'chromeos', 'Chrome OS Wallpapers'], [True, 'earthview', 'Google Earth View Wallpapers']]'
INFO: 2020-06-27 09:05:57,815: log_options() 'stats_enabled = True'
INFO: 2020-06-27 09:05:57,815: log_options() 'stats_notice_shown = False'
INFO: 2020-06-27 09:05:57,815: log_options() 'sync_enabled = True'
INFO: 2020-06-27 09:05:57,815: log_options() 'use_landscape_enabled = True'
INFO: 2020-06-27 09:05:57,815: reload_config() 'No need to clear prepared queue'
INFO: 2020-06-27 09:05:57,815: update_indicator() 'Setting file info to: /home/saul/Pictures/wallpaper/Downloaded by Variety/Bing/OHR.WhiteRimTrail_EN-US2749200524_1920x1080.jpg'
INFO: 2020-06-27 09:05:57,817: load_last_change_time() 'Change interval < 6 hours, ignore persisted last_change_time, wait initially the whole interval: 300'
INFO: 2020-06-27 09:05:57,817: update_indicator() 'Setting file info to: /home/saul/Pictures/wallpaper/Downloaded by Variety/Bing/OHR.WhiteRimTrail_EN-US2749200524_1920x1080.jpg'
INFO: 2020-06-27 09:05:57,817: regular_change_thread() 'regular_change thread running'
INFO: 2020-06-27 09:05:57,818: prepare_thread() 'Prepare thread running'
INFO: 2020-06-27 09:05:57,818: prepare_thread() 'Prepared buffer contains 0 images'
INFO: 2020-06-27 09:05:57,818: prepare_thread() 'Preparing some images'
INFO: 2020-06-27 09:05:57,818: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:05:57,818: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:05:57,819: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:05:57,819: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:05:57,819: download_one() 'Chrome OS Wallpapers: Downloading an image, config: None'
INFO: 2020-06-27 09:05:57,819: download_one() 'Chrome OS Wallpapers: Queue size: 0'
INFO: 2020-06-27 09:05:57,819: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:05:57,819: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:05:57,819: download_one() 'Chrome OS Wallpapers: Filling queue'
ERROR: 2020-06-27 09:05:57,825: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f53cdcf9880>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /chromeos-wallpaper-public/manifest_en.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53cdcf9880>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1159, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.8/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/ChromeOSWallpapersDownloader.py", line 54, in fill_queue
    manifest = Util.fetch_json(MANIFEST_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 612, in request
    r = requests.request(
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /chromeos-wallpaper-public/manifest_en.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53cdcf9880>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
INFO: 2020-06-27 09:05:57,894: prepare_thread() 'After search prepared buffer contains 53 images'
INFO: 2020-06-27 09:05:57,917: do_set_wp() 'Calling do_set_wp with /home/saul/Pictures/wallpaper/Downloaded by Variety/Bing/OHR.WhiteRimTrail_EN-US2749200524_1920x1080.jpg, time: 1593241557.9172778'
INFO: 2020-06-27 09:05:57,927: update_indicator() 'Setting file info to: /home/saul/Pictures/wallpaper/Downloaded by Variety/Bing/OHR.WhiteRimTrail_EN-US2749200524_1920x1080.jpg'
INFO: 2020-06-27 09:05:58,829: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:05:58,830: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:05:58,830: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:05:58,831: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:05:58,831: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-06-27 09:05:58,831: download_one() 'Bing: Queue size: 0'
INFO: 2020-06-27 09:05:58,831: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:05:58,831: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:05:58,831: download_one() 'Bing: Filling queue'
ERROR: 2020-06-27 09:05:58,836: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f53cc2bbf40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.bing.com', port=443): Max retries exceeded with url: /HPImageArchive.aspx?format=js&idx=0&n=100&mkt=en-US (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53cc2bbf40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1159, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.8/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/BingDownloader.py", line 61, in fill_queue
    s = Util.fetch_json(BingDownloader.BING_JSON_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 612, in request
    r = requests.request(
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.bing.com', port=443): Max retries exceeded with url: /HPImageArchive.aspx?format=js&idx=0&n=100&mkt=en-US (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53cc2bbf40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
INFO: 2020-06-27 09:05:59,241: reload() 'Reloading preferences dialog'
INFO: 2020-06-27 09:05:59,894: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2020-06-27 09:06:02,818: set_wallpaper() 'Calling set_wallpaper with /home/saul/Pictures/wallpaper/Downloaded by Variety/Earth View/Diomede Ilands (ID-1645).jpg'
INFO: 2020-06-27 09:06:02,819: prepare_thread() 'Prepared buffer contains 53 images'
INFO: 2020-06-27 09:06:02,821: do_set_wp() 'Calling do_set_wp with /home/saul/Pictures/wallpaper/Downloaded by Variety/Earth View/Diomede Ilands (ID-1645).jpg, time: 1593241562.821505'
INFO: 2020-06-27 09:06:02,837: regular_change_thread() 'regular_change: waiting till user resumes'
INFO: 2020-06-27 09:06:02,862: update_indicator() 'Setting file info to: /home/saul/Pictures/wallpaper/Downloaded by Variety/Earth View/Diomede Ilands (ID-1645).jpg'
INFO: 2020-06-27 09:06:04,820: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2020-06-27 09:06:04,821: trigger_download() 'Triggering download thread to check if download needed'
INFO: 2020-06-27 09:06:04,822: get_throttling() 'Earth View: parsing serverside options'
INFO: 2020-06-27 09:06:04,823: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2020-06-27 09:06:04,824: get_throttling() 'Earth View: parsing serverside options'
INFO: 2020-06-27 09:06:04,824: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2020-06-27 09:06:04,824: download_one() 'Earth View: Downloading an image, config: None'
INFO: 2020-06-27 09:06:04,824: download_one() 'Earth View: Queue size: 0'
INFO: 2020-06-27 09:06:04,825: get_throttling() 'Earth View: parsing serverside options'
INFO: 2020-06-27 09:06:04,825: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2020-06-27 09:06:04,825: download_one() 'Earth View: Filling queue'
ERROR: 2020-06-27 09:06:04,835: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f53b04712e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /limhenry/earthview/3cd868a932cd652c4373c0f6ea8618a96b08be4e/wallpaper%20changer/data.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53b04712e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1159, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.8/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/EarthviewDownloader.py", line 57, in fill_queue
    queue = Util.fetch_json(DATA_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 612, in request
    r = requests.request(
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /limhenry/earthview/3cd868a932cd652c4373c0f6ea8618a96b08be4e/wallpaper%20changer/data.json (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f53b04712e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
INFO: 2020-06-27 09:06:17,839: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2020-06-27 09:06:17,846: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1240, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1286, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1235, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1006, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 946, in send
    self.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f53b0471730>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53b0471730>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1087, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 612, in request
    r = requests.request(
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='tiny.cc', port=80): Max retries exceeded with url: /variety-options-063 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f53b0471730>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
INFO: 2020-06-27 09:06:47,880: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2020-06-27 09:06:54,254: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='tiny.cc', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1087, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 612, in request
    r = requests.request(
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen]
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='tiny.cc', port=443): Read timed out. (read timeout=5)
INFO: 2020-06-27 09:07:24,286: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2020-06-27 09:07:30,496: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='tiny.cc', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1087, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 612, in request
    r = requests.request(
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen]
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='tiny.cc', port=443): Read timed out. (read timeout=5)
INFO: 2020-06-27 09:08:00,527: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
ERROR: 2020-06-27 09:08:06,756: server_options_thread() 'Could not fetch Variety serverside options'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.8/http/client.py", line 1332, in getresponse
    response.begin()
  File "/usr/lib/python3.8/http/client.py", line 303, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.8/http/client.py", line 264, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.8/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.8/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 724, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 403, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 428, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='tiny.cc', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1087, in server_options_thread
    self.server_options = Util.fetch_json(VarietyWindow.SERVERSIDE_OPTIONS_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 612, in request
    r = requests.request(
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 665, in send
    history = [resp for resp in gen]
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 665, in <listcomp>
    history = [resp for resp in gen]
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='tiny.cc', port=443): Read timed out. (read timeout=5)
INFO: 2020-06-27 09:08:36,783: server_options_thread() 'Fetching server options from http://tiny.cc/variety-options-063'
INFO: 2020-06-27 09:08:38,427: server_options_thread() 'Fetched server options: {'flickr': {'min_fill_queue_interval': 1200, 'min_download_interval': 1200}, 'wallbase': {'min_fill_queue_interval': 1800, 'min_download_interval': 1800}, 'wallhaven': {'min_fill_queue_interval': 1800, 'min_download_interval': 1800}, 'wallpapers.net': {'min_fill_queue_interval': 601, 'min_download_interval': 0}, 'unsplash': {'min_fill_queue_interval': 20000000000, 'min_download_interval': 20000000000}, 'unsplash_v2': {'min_fill_queue_interval': 2000, 'min_download_interval': 1200}, 'status_message': {'0.0.1': '', '*': ''}}'
INFO: 2020-06-27 09:09:05,840: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:09:05,841: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:09:05,841: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:09:05,841: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:09:05,841: download_one() 'Chrome OS Wallpapers: Downloading an image, config: None'
INFO: 2020-06-27 09:09:05,841: download_one() 'Chrome OS Wallpapers: Queue size: 0'
INFO: 2020-06-27 09:09:05,842: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:09:05,842: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:09:05,842: download_one() 'Chrome OS Wallpapers: Filling queue'
ERROR: 2020-06-27 09:09:06,818: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1159, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.8/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/ChromeOSWallpapersDownloader.py", line 54, in fill_queue
    manifest = Util.fetch_json(MANIFEST_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 622, in request
    r.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/chromeos-wallpaper-public/manifest_en.json
INFO: 2020-06-27 09:09:07,820: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:09:07,821: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:09:07,821: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:09:07,821: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:09:07,821: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-06-27 09:09:07,822: download_one() 'Bing: Queue size: 0'
INFO: 2020-06-27 09:09:07,822: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:09:07,822: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:09:07,822: download_one() 'Bing: Filling queue'
INFO: 2020-06-27 09:09:08,341: download_one() 'Bing: Queue populated with 7 URLs'
INFO: 2020-06-27 09:09:08,342: save_locally() 'Origin URL: https://www.bing.com/search?q=Santuario+Madonna+della+Corona&form=hpcapt&filters=HpDate%3a%2220200627_0700%22'
INFO: 2020-06-27 09:09:08,342: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.MtBaldoSantuario_EN-US6460114986_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2020-06-27 09:09:08,342: save_locally() 'Local path: /home/saul/Pictures/wallpaper/Downloaded by Variety/Bing/OHR.MtBaldoSantuario_EN-US6460114986_1920x1080.jpg'
INFO: 2020-06-27 09:09:09,644: save_locally() 'Download complete'
INFO: 2020-06-27 09:09:09,645: update_indicator() 'Setting file info to: /home/saul/Pictures/wallpaper/Downloaded by Variety/Earth View/Diomede Ilands (ID-1645).jpg'
INFO: 2020-06-27 09:09:09,654: download_one_from() 'Adding downloaded file /home/saul/Pictures/wallpaper/Downloaded by Variety/Bing/OHR.MtBaldoSantuario_EN-US6460114986_1920x1080.jpg to unseen_downloads'
INFO: 2020-06-27 09:09:10,656: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:09:10,656: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:09:10,657: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:09:10,657: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:09:10,657: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-06-27 09:09:10,657: download_one() 'Bing: Queue size: 6'
INFO: 2020-06-27 09:09:10,657: download_one() 'Bing: Queue populated with 6 URLs'
INFO: 2020-06-27 09:09:10,658: save_locally() 'Origin URL: https://www.bing.com/search?q=southern+double-collared+sunbird&form=hpcapt&filters=HpDate%3a%2220200622_0700%22'
INFO: 2020-06-27 09:09:10,658: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.SouthernSunbird_EN-US5701754937_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2020-06-27 09:09:10,659: save_locally() 'Local path: /home/saul/Pictures/wallpaper/Downloaded by Variety/Bing/OHR.SouthernSunbird_EN-US5701754937_1920x1080.jpg'
INFO: 2020-06-27 09:09:10,659: save_locally() 'File already exists, skip downloading'
INFO: 2020-06-27 09:09:11,661: get_throttling() 'Earth View: parsing serverside options'
INFO: 2020-06-27 09:09:11,661: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2020-06-27 09:09:11,662: get_throttling() 'Earth View: parsing serverside options'
INFO: 2020-06-27 09:09:11,662: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2020-06-27 09:09:11,662: download_one() 'Earth View: Downloading an image, config: None'
INFO: 2020-06-27 09:09:11,662: download_one() 'Earth View: Queue size: 0'
INFO: 2020-06-27 09:09:11,662: get_throttling() 'Earth View: parsing serverside options'
INFO: 2020-06-27 09:09:11,662: get_throttling() 'Could not parse Earth View serverside options, using defaults 20, None'
INFO: 2020-06-27 09:09:11,662: download_one() 'Earth View: Filling queue'
INFO: 2020-06-27 09:09:12,752: download_one() 'Earth View: Queue populated with 1511 URLs'
INFO: 2020-06-27 09:09:12,753: save_locally() 'Origin URL: https://earthview.withgoogle.com/1724'
INFO: 2020-06-27 09:09:12,753: save_locally() 'Image URL: https://www.gstatic.com/prettyearth/assets/full/1724.jpg'
INFO: 2020-06-27 09:09:12,753: save_locally() 'Local path: /home/saul/Pictures/wallpaper/Downloaded by Variety/Earth View/Al Jahra, Kuwait (ID-1724).jpg'
INFO: 2020-06-27 09:09:15,006: save_locally() 'Download complete'
INFO: 2020-06-27 09:09:15,006: update_indicator() 'Setting file info to: /home/saul/Pictures/wallpaper/Downloaded by Variety/Earth View/Diomede Ilands (ID-1645).jpg'
INFO: 2020-06-27 09:09:15,011: download_one_from() 'Adding downloaded file /home/saul/Pictures/wallpaper/Downloaded by Variety/Earth View/Al Jahra, Kuwait (ID-1724).jpg to unseen_downloads'
INFO: 2020-06-27 09:12:16,014: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:12:16,014: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:12:16,014: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:12:16,015: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:12:16,015: download_one() 'Chrome OS Wallpapers: Downloading an image, config: None'
INFO: 2020-06-27 09:12:16,015: download_one() 'Chrome OS Wallpapers: Queue size: 0'
INFO: 2020-06-27 09:12:16,015: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:12:16,015: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:12:16,015: download_one() 'Chrome OS Wallpapers: Filling queue'
ERROR: 2020-06-27 09:12:16,709: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1159, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.8/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/ChromeOSWallpapersDownloader.py", line 54, in fill_queue
    manifest = Util.fetch_json(MANIFEST_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 622, in request
    r.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/chromeos-wallpaper-public/manifest_en.json
INFO: 2020-06-27 09:12:17,710: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:12:17,711: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:12:17,711: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:12:17,711: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:12:17,711: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-06-27 09:12:17,711: download_one() 'Bing: Queue size: 5'
INFO: 2020-06-27 09:12:17,712: download_one() 'Bing: Queue populated with 5 URLs'
INFO: 2020-06-27 09:12:17,712: save_locally() 'Origin URL: https://www.bing.com/search?q=midsummer+sweden&form=hpcapt&filters=HpDate%3a%2220200624_0700%22'
INFO: 2020-06-27 09:12:17,712: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.MidsummerEve_EN-US0497687586_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2020-06-27 09:12:17,712: save_locally() 'Local path: /home/saul/Pictures/wallpaper/Downloaded by Variety/Bing/OHR.MidsummerEve_EN-US0497687586_1920x1080.jpg'
INFO: 2020-06-27 09:12:17,712: save_locally() 'File already exists, skip downloading'
INFO: 2020-06-27 09:15:18,714: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:15:18,715: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:15:18,715: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:15:18,715: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:15:18,715: download_one() 'Chrome OS Wallpapers: Downloading an image, config: None'
INFO: 2020-06-27 09:15:18,715: download_one() 'Chrome OS Wallpapers: Queue size: 0'
INFO: 2020-06-27 09:15:18,716: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:15:18,716: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:15:18,716: download_one() 'Chrome OS Wallpapers: Filling queue'
ERROR: 2020-06-27 09:15:19,607: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1159, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.8/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/ChromeOSWallpapersDownloader.py", line 54, in fill_queue
    manifest = Util.fetch_json(MANIFEST_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 622, in request
    r.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/chromeos-wallpaper-public/manifest_en.json
INFO: 2020-06-27 09:15:20,610: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:15:20,611: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:15:20,611: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:15:20,611: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:15:20,611: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-06-27 09:15:20,611: download_one() 'Bing: Queue size: 4'
INFO: 2020-06-27 09:15:20,611: download_one() 'Bing: Queue populated with 4 URLs'
INFO: 2020-06-27 09:15:20,612: save_locally() 'Origin URL: https://www.bing.com/search?q=North+Devon+England&form=hpcapt&filters=HpDate%3a%2220200623_0700%22'
INFO: 2020-06-27 09:15:20,612: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.BullPoint_EN-US5814716721_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2020-06-27 09:15:20,612: save_locally() 'Local path: /home/saul/Pictures/wallpaper/Downloaded by Variety/Bing/OHR.BullPoint_EN-US5814716721_1920x1080.jpg'
INFO: 2020-06-27 09:15:20,612: save_locally() 'File already exists, skip downloading'
INFO: 2020-06-27 09:18:21,615: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:18:21,616: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:18:21,616: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:18:21,616: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:18:21,616: download_one() 'Chrome OS Wallpapers: Downloading an image, config: None'
INFO: 2020-06-27 09:18:21,617: download_one() 'Chrome OS Wallpapers: Queue size: 0'
INFO: 2020-06-27 09:18:21,617: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:18:21,617: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:18:21,617: download_one() 'Chrome OS Wallpapers: Filling queue'
ERROR: 2020-06-27 09:18:22,426: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1159, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.8/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/ChromeOSWallpapersDownloader.py", line 54, in fill_queue
    manifest = Util.fetch_json(MANIFEST_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 622, in request
    r.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/chromeos-wallpaper-public/manifest_en.json
INFO: 2020-06-27 09:18:23,429: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:18:23,429: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:18:23,429: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:18:23,429: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:18:23,429: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-06-27 09:18:23,429: download_one() 'Bing: Queue size: 3'
INFO: 2020-06-27 09:18:23,429: download_one() 'Bing: Queue populated with 3 URLs'
INFO: 2020-06-27 09:18:23,429: save_locally() 'Origin URL: https://www.bing.com/search?q=madagascar+independence+day&form=hpcapt&filters=HpDate%3a%2220200626_0700%22'
INFO: 2020-06-27 09:18:23,429: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.AdansoniaGrandidieri_EN-US6269745972_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2020-06-27 09:18:23,430: save_locally() 'Local path: /home/saul/Pictures/wallpaper/Downloaded by Variety/Bing/OHR.AdansoniaGrandidieri_EN-US6269745972_1920x1080.jpg'
INFO: 2020-06-27 09:18:23,430: save_locally() 'File already exists, skip downloading'
INFO: 2020-06-27 09:21:24,431: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:21:24,432: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:21:24,432: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:21:24,432: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:21:24,432: download_one() 'Chrome OS Wallpapers: Downloading an image, config: None'
INFO: 2020-06-27 09:21:24,432: download_one() 'Chrome OS Wallpapers: Queue size: 0'
INFO: 2020-06-27 09:21:24,433: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:21:24,433: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:21:24,433: download_one() 'Chrome OS Wallpapers: Filling queue'
ERROR: 2020-06-27 09:21:25,389: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1159, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.8/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/ChromeOSWallpapersDownloader.py", line 54, in fill_queue
    manifest = Util.fetch_json(MANIFEST_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 622, in request
    r.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/chromeos-wallpaper-public/manifest_en.json
INFO: 2020-06-27 09:21:26,390: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:21:26,391: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:21:26,391: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:21:26,391: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:21:26,391: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-06-27 09:21:26,391: download_one() 'Bing: Queue size: 2'
INFO: 2020-06-27 09:21:26,392: download_one() 'Bing: Queue populated with 2 URLs'
INFO: 2020-06-27 09:21:26,392: save_locally() 'Origin URL: https://www.bing.com/search?q=hierapolis+turkey&form=hpcapt&filters=HpDate%3a%2220200621_0700%22'
INFO: 2020-06-27 09:21:26,392: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.HierapolisTurkey_EN-US8458061534_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2020-06-27 09:21:26,392: save_locally() 'Local path: /home/saul/Pictures/wallpaper/Downloaded by Variety/Bing/OHR.HierapolisTurkey_EN-US8458061534_1920x1080.jpg'
INFO: 2020-06-27 09:21:26,392: save_locally() 'File already exists, skip downloading'
INFO: 2020-06-27 09:24:27,395: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:24:27,396: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:24:27,396: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:24:27,396: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:24:27,397: download_one() 'Chrome OS Wallpapers: Downloading an image, config: None'
INFO: 2020-06-27 09:24:27,397: download_one() 'Chrome OS Wallpapers: Queue size: 0'
INFO: 2020-06-27 09:24:27,397: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:24:27,397: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:24:27,397: download_one() 'Chrome OS Wallpapers: Filling queue'
ERROR: 2020-06-27 09:24:28,071: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1159, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.8/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/ChromeOSWallpapersDownloader.py", line 54, in fill_queue
    manifest = Util.fetch_json(MANIFEST_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 622, in request
    r.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/chromeos-wallpaper-public/manifest_en.json
INFO: 2020-06-27 09:24:29,074: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:24:29,074: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:24:29,075: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:24:29,075: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:24:29,075: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-06-27 09:24:29,075: download_one() 'Bing: Queue size: 1'
INFO: 2020-06-27 09:24:29,075: download_one() 'Bing: Queue populated with 1 URLs'
INFO: 2020-06-27 09:24:29,076: save_locally() 'Origin URL: https://www.bing.com/search?q=gorch+fock+1958&form=hpcapt&filters=HpDate%3a%2220200625_0700%22'
INFO: 2020-06-27 09:24:29,076: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.GorchFock_EN-US6157323134_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2020-06-27 09:24:29,076: save_locally() 'Local path: /home/saul/Pictures/wallpaper/Downloaded by Variety/Bing/OHR.GorchFock_EN-US6157323134_1920x1080.jpg'
INFO: 2020-06-27 09:24:29,076: save_locally() 'File already exists, skip downloading'
INFO: 2020-06-27 09:27:30,079: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:27:30,079: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:27:30,080: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:27:30,080: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:27:30,080: download_one() 'Chrome OS Wallpapers: Downloading an image, config: None'
INFO: 2020-06-27 09:27:30,080: download_one() 'Chrome OS Wallpapers: Queue size: 0'
INFO: 2020-06-27 09:27:30,080: get_throttling() 'Chrome OS Wallpapers: parsing serverside options'
INFO: 2020-06-27 09:27:30,080: get_throttling() 'Could not parse Chrome OS Wallpapers serverside options, using defaults None, None'
INFO: 2020-06-27 09:27:30,081: download_one() 'Chrome OS Wallpapers: Filling queue'
ERROR: 2020-06-27 09:27:30,957: download_one_from() 'Could not download wallpaper:'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/variety/VarietyWindow.py", line 1159, in download_one_from
    file = downloader.download_one()
  File "/usr/lib/python3.8/site-packages/variety/plugins/downloaders/DefaultDownloader.py", line 141, in download_one
    items = self.fill_queue()
  File "/usr/lib/python3.8/site-packages/variety/plugins/builtin/downloaders/ChromeOSWallpapersDownloader.py", line 54, in fill_queue
    manifest = Util.fetch_json(MANIFEST_URL)
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 643, in fetch_json
    return Util.request(url, data, **request_kwargs).json()
  File "/usr/lib/python3.8/site-packages/variety/Util.py", line 622, in request
    r.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://storage.googleapis.com/chromeos-wallpaper-public/manifest_en.json
INFO: 2020-06-27 09:27:31,960: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:27:31,960: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:27:31,961: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:27:31,961: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:27:31,961: download_one() 'Bing: Downloading an image, config: None'
INFO: 2020-06-27 09:27:31,961: download_one() 'Bing: Queue size: 0'
INFO: 2020-06-27 09:27:31,961: get_throttling() 'Bing: parsing serverside options'
INFO: 2020-06-27 09:27:31,962: get_throttling() 'Could not parse Bing serverside options, using defaults None, None'
INFO: 2020-06-27 09:27:31,962: download_one() 'Bing: Filling queue'
INFO: 2020-06-27 09:27:32,478: download_one() 'Bing: Queue populated with 7 URLs'
INFO: 2020-06-27 09:27:32,479: save_locally() 'Origin URL: https://www.bing.com/search?q=southern+double-collared+sunbird&form=hpcapt&filters=HpDate%3a%2220200622_0700%22'
INFO: 2020-06-27 09:27:32,479: save_locally() 'Image URL: https://www.bing.com/th?id=OHR.SouthernSunbird_EN-US5701754937_1920x1080.jpg&rf=LaDigue_1920x1080.jpg&pid=hp'
INFO: 2020-06-27 09:27:32,479: save_locally() 'Local path: /home/saul/Pictures/wallpaper/Downloaded by Variety/Bing/OHR.SouthernSunbird_EN-US5701754937_1920x1080.jpg'
INFO: 2020-06-27 09:27:32,479: save_locally() 'File already exists, skip downloading'
